samples: ["NA12878"]

coverage: [5]

total_coverage: 30

read_length: 100

nreads: 14500000

index: "data/chr21.fa"

vcf: "data/chr21.vcf.gz"

beagle_map: "data/plink.chr21.GRCh37.map"

shapeit_map: "data/chr21.b37.gmap.gz"
