samples: ["NA12878"]

coverage: [10]

total_coverage: 60

read_length: 100

nreads: 28877067 # this is technically 60x coverage

index: "data/chr21.fa"

vcf: "data/chr21.vcf.gz"

beagle_map: "data/plink.chr21.GRCh37.map"

shapeit_map: "data/chr21.b37.gmap.gz"
