samples: ["NA12878"]

coverage: [1, 2, 5, 10, 20, 30]

total_coverage: 60

read_length: 100

nreads: 14438968 # this is technically 15x coverage for each haplotype

hg19_index: "data/chr21.fa"

vcf: "data/chr21.vcf.gz"

beagle_map: "data/plink.chr21.GRCh37.map"

shapeit_map: "data/chr21.b37.gmap.gz"

