n_test_samples: 5

coverage: [1, 2, 5, 10, 20]

total_coverage: 30

read_length: 100

n_train_reads: 14438968 # this is technically 15x coverage for each haplotype

n_test_reads: 2000000

hg19_index: "data/chr21.fa"

vcf: "data/chr21.vcf.gz"

beagle_map: "data/plink.chr21.GRCh37.map"

frac_alt: 0.06

repeat_bed: "data/chr21_repeats.bed"
